### ISSUE TITLE
فيه مشكله في ال cclient

### ISSUE THREAD

**Issue by Onlylece** [justalghamdi/dvRAT#2]
في مكتبة ال json انه فيه مشكله اني مش منزلها و انا منزلها
![unknown](https://user-images.githubusercontent.com/90127911/180663103-deccb092-be88-4ca5-a460-2cd6a943dc6a.png)

**Comment by justalghamdi** [comment]
تأكد من أنك محمله عن طريق vcpkg  ايضا تأكد ان vcpkg مربوط مع visual studio ايضا تأكد انك تحمل نسخة ال release و ال debug لل json-c
